### PR TITLE
Swift 4 update

### PR DESCRIPTION
**Pull request by edopelawi**
Per #14 's request.

### CODE REVIEW

**Comment by leedsalex** [comment]
@edopelawi Thank you for taking care of this for me in such a timely manner.

**Comment by edopelawi** [comment]
Sure thing, @leedsalex! I'm still trying to get the configuration right for Travis CI's Xcode 9, could you use the branch directly (swift-4-update) from your Carthage / Cocoapods? I'll let you know when it's properly merged and released.

**Comment by leedsalex** [comment]
@edopelawi Any update on your progress? Is there anything I can help with?

**Comment by edopelawi** [comment]
Hey @leedsalex, thanks for bumping this issue. Got caught in a middle of a busy project. 

The travis compile issue was caused by Nimble v7.0.2 and Quick v1.0.1 which can't run in Xcode 9. The Quick team already updated Nimble 7.0.2, but not with the Quick. I've posted an issue for it [here](https://github.com/Quick/Quick/issues/748).

For the time being, I skipped running tests for my Travis build step. I have run all the tests in my machine to make sure that runs well. After the newest builds succeeds, I'll publish the newest version.

Cheers,

**Pull request merged**
