### PR TITLE
Fix Carthage Build Error

### PR DESCRIPTION
**Pull request by leedsalex**
This fixes the Carthage build error experienced in Carthage version 0.26.2 (#16).
A small change was made to the project build settings to use Xcode Default build directory instead of a target defined build directory.

### CODE REVIEW

**Comment by edopelawi** [comment]
Hey @leedsalex, thanks for the pull request! Apologies for not responding to your issue, I got my hands full with my day-to-day work these few weeks. Definitely will check this out this evening.

By the way, a suggestion from me - could you change the merge target to the develop branch? That way, I could update the CHANGELOG and test it on Cocoapods before releasing it... just to make sure 🤞 

Cheers mate!

**Comment by leedsalex** [comment]
Thanks @edopelawi I've switched the base branch to develop.

**Comment by leedsalex** [comment]
@edopelawi Were you able to take a look at this pull request?

**Comment by edopelawi** [comment]
Whoops, I missed this pull request. Works like a charm mate, merging this now! @leedsalex

**Pull request merged**
