### PR TITLE
Update Framework to Swift 4.2

### PR DESCRIPTION
**Pull request by leedsalex**
I updated the framework to Swift 4.2 / Xcode 10. However, I wasn't able to update the example project, as I don't use CocoaPods.

### CODE REVIEW

**Comment by leedsalex** [comment]
@edopelawi Could you review this?

**Comment by edopelawi** [comment]
hey @leedsalex , thanks for the pull request! I just got the time, checking it out!

**Comment by edopelawi** [comment]
Hey Alex, I know this has been forever, but... I just got the time to upgrade it to 4.2, man. Thanks a lot for the help, your pull request is a great reference.

I'm closing this now!

**Comment by leedsalex** [comment]
Thanks @edopelawi 

Any chance you can upgrade to Swift 5.1? Swift 4.2 has come and gone.

**Comment by edopelawi** [comment]
Yep! I'm trying to do both 5 and 5.1 right now.

**Pull request closed without merging**
